---
exclude_paths:
  - "dialogy/plugins/__init__.py"
  - "dialogy/parser/text/entity/__init__.py"
  - "dialogy/postprocess/text/__init__.py"
  - "dialogy/constants/__init__.py"
  - "dialogy/errors/__init__.py"
  - "dialogy/types/entity/__init__.py"
  - "dialogy/types/intent/__init__.py"
  - "dialogy/plugin/plugin.py"
  - "dialogy/parser/text/entity/duckling_parser/__init__.py"
  - "dialogy/parser/text/entity/__init__.py"
  - "dialogy/parser/text/__init__.py"
  - "dialogy/parser/__init__.py"
  - "dialogy/__init__.py"
  - "dialogy/workflow/__init__.py"
  - "dialogy/types/__init__.py"
  - "dialogy/utils/__init__.py"
  - "tests/**"
  - "docs/**"
  - "docs_src/**"
  - ".github/**"
  - "*.md"
